name: Build

on:
  push:
    branches:
      - "*"

jobs:
  Build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: |
          ./docker_build.sh build
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifacts
          path: artifacts
        
      - name: Parse unit test results
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Unit test results
          path: artifacts/UnitTests/*.trx
          reporter: dotnet-trx
          list-suites: 'failed'
          fail-on-error: 'true'
